#!/usr/bin/env sh

usage="Usage: $0 pkgbuild-rootdir"

[ ! -d "$1" ] && { echo "$usage"; exit 1; }
# Set a default chroot location unless already defined.
[ ! -d "$CHROOT" ] && export CHROOT=$HOME/.local/abs/build

# Update pkgbuild with a new md5 (these need to be verified with upstream
# checksums manually) and attempt building in a chroot. Generates a source
# package ready to upload to the AUR on successful builds.
cd "$1" &&
    sed -i "/^md5sums=/ s/.*/$(makepkg --geninteg)/" PKGBUILD &&
    sudo makechrootpkg -r $CHROOT -n -- --syncdeps --log --clean &&
    makepkg --source
